from __future__ import annotations

from collections.abc import AsyncIterator, Mapping, Sequence
from typing import Any, Protocol, runtime_checkable

from algen_agent_runtime.retrieval.contracts import (
    RetrievalQuery,
    RetrievedDocument,
    SourceDocument,
)
from algen_agent_runtime.types.contracts import (
    AgentDefinition,
    Artifact,
    Message,
    ModelCapabilities,
    ModelRequest,
    ModelResponse,
    ModelStreamEvent,
    RunRequest,
    RunResult,
    RunState,
)


@runtime_checkable
class ModelProvider(Protocol):
    @property
    def provider_id(self) -> str: ...
    async def capabilities(self, model: str) -> ModelCapabilities: ...
    async def generate(self, request: ModelRequest) -> ModelResponse: ...
    def stream(self, request: ModelRequest) -> AsyncIterator[ModelStreamEvent]: ...
    async def embed(self, texts: Sequence[str], model: str | None = None) -> list[list[float]]: ...
    async def health(self) -> bool: ...


class SecretProvider(Protocol):
    async def get(self, reference: str) -> str: ...


class Planner(Protocol):
    @property
    def name(self) -> str: ...
    async def plan(self, state: RunState, agent: AgentDefinition) -> Any: ...


class ContextBuilder(Protocol):
    @property
    def name(self) -> str: ...
    async def build(self, state: RunState, agent: AgentDefinition) -> Sequence[Message]: ...


class Retriever(Protocol):
    async def retrieve(self, query: RetrievalQuery) -> Sequence[RetrievedDocument]: ...


class DocumentIndexer(Protocol):
    async def ingest(self, documents: Sequence[SourceDocument]) -> int: ...
    async def delete(self, tenant_id: str, document_id: str) -> int: ...


class VectorStore(Retriever, DocumentIndexer, Protocol):
    """Combined retrieval and indexing boundary implemented by vector backends."""


class PolicyEngine(Protocol):
    async def evaluate(self, point: str, payload: Any, context: Mapping[str, Any]) -> Any: ...


class Verifier(Protocol):
    @property
    def name(self) -> str: ...
    async def verify(self, value: Any, context: Mapping[str, Any]) -> Any: ...


class ResponseComposer(Protocol):
    @property
    def name(self) -> str: ...
    async def compose(self, state: RunState) -> RunResult: ...


class RunStore(Protocol):
    async def create(self, state: RunState) -> None: ...
    async def get(self, run_id: str, tenant_id: str) -> RunState | None: ...
    async def save(self, state: RunState, expected_version: int) -> None: ...
    async def list_active(self, limit: int = 1000) -> Sequence[RunState]: ...


class MemoryStore(Protocol):
    async def append(
        self, tenant_id: str, session_id: str, messages: Sequence[Message]
    ) -> None: ...
    async def get(self, tenant_id: str, session_id: str, limit: int) -> Sequence[Message]: ...
    async def delete(self, tenant_id: str, session_id: str) -> None: ...


class ArtifactStore(Protocol):
    async def put(self, artifact: Artifact) -> None: ...
    async def get(self, artifact_id: str, tenant_id: str) -> Artifact | None: ...


class AuditLog(Protocol):
    async def append(self, event: Any) -> None: ...
    async def list(self, tenant_id: str, resource_id: str | None = None) -> Sequence[Any]: ...


class AgentRegistry(Protocol):
    def register(self, definition: AgentDefinition) -> None: ...
    def get(self, name: str, version: str | None = None) -> AgentDefinition: ...
    def list(self) -> Sequence[AgentDefinition]: ...


class EventPublisher(Protocol):
    async def publish(self, event: Any) -> None: ...
    async def next_sequence(self, run_id: str) -> int: ...
    async def history(self, run_id: str, after: int = 0) -> Sequence[Any]: ...
    def subscribe(self, run_id: str, after: int = 0) -> AsyncIterator[Any]: ...


class Runtime(Protocol):
    async def start(self, request: RunRequest) -> RunState: ...
    async def run(self, request: RunRequest) -> RunResult: ...
    async def wait(self, run_id: str, tenant_id: str) -> RunResult: ...
    async def cancel(self, run_id: str, tenant_id: str) -> RunState: ...
    async def resume(self, run_id: str, tenant_id: str, payload: Mapping[str, Any]) -> RunState: ...
