"""Deterministic project scaffolding for Algen Agent Runtime."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Literal

TemplateName = Literal["agent", "approval", "workflow"]
AVAILABLE_TEMPLATES: tuple[TemplateName, ...] = ("agent", "approval", "workflow")


def _sanitize_name(name: str) -> tuple[str, str]:
    """Return (slug, python_identifier) from user project name."""
    cleaned = re.sub(r"[^\w\-]", "", name).strip("_-")
    if not cleaned:
        raise ValueError(f"Invalid project name {name!r}: must contain alphanumeric characters")
    slug = cleaned.lower().replace("_", "-")
    ident = cleaned.lower().replace("-", "_")
    if not ident[0].isalpha():
        ident = f"agent_{ident}"
    return slug, ident


def _gitignore_content() -> str:
    return """# Environments and dependencies
.venv/
env/
venv/
__pycache__/
*.py[cod]

# Secrets and local configurations
.env
.env.*
*.key
*.pem

# Runtime persistence and artifacts
artifacts/
*.sqlite
*.db
.pytest_cache/
.coverage
"""


def _traccia_example_content() -> str:
    return """# Traccia Telemetry Configuration Example
# Copy to traccia.toml and configure as needed.

[project]
name = "algen-project"
version = "0.1.0"

[telemetry]
enabled = false
sample_rate = 1.0
endpoint = "http://127.0.0.1:4318/v1/traces"
"""


def _agent_template(slug: str, ident: str) -> dict[str, str]:
    agent_yaml = f"""providers:
  mock:
    type: mock
    default_model: deterministic

agents:
  - name: {slug}
    version: 1.0.0
    description: Deterministic offline agent generated by algen-agent-runtime
    system_instructions: You are a helpful, concise assistant. Return direct answers.
    default_model:
      name: default
      provider: mock
      model: deterministic
    planning_strategy: direct
    max_steps: 5
"""

    app_py = f'''from __future__ import annotations

import argparse
import asyncio
from pathlib import Path

from algen_agent_runtime.config.settings import load_settings
from algen_agent_runtime.orchestration.container import build_container
from algen_agent_runtime.runtime.client import AlgenAgentRuntimeClient
from algen_agent_runtime.types.contracts import RunRequest


async def run(question: str) -> str:
    """Execute the {slug} agent with the given question."""
    config_path = Path(__file__).with_name("agent.yaml")
    settings = load_settings((config_path,))
    container = build_container(settings)
    try:
        client = AlgenAgentRuntimeClient(container.runtime)
        result = await client.run(
            RunRequest(
                agent="{slug}",
                input=question,
                tenant_id="default-tenant",
                user_id="default-user",
            )
        )
        if result.error:
            raise RuntimeError(result.error)
        return result.output or ""
    finally:
        container.close()


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Run {slug}")
    parser.add_argument("question", nargs="?", default="Hello, what can you do?")
    args = parser.parse_args(argv)
    output = asyncio.run(run(args.question))
    print(output)


if __name__ == "__main__":
    main()
'''

    test_py = """from __future__ import annotations

import pytest
from app import run


@pytest.mark.asyncio
async def test_agent_runs_offline() -> None:
    output = await run("Hello")
    assert output
"""

    readme_md = f"""# {slug}

An agent built with [Algen Agent Runtime](https://github.com/AlgenAI/algen-agent-runtime).

## Getting Started

Run the agent offline with the built-in deterministic mock provider:

```bash
python app.py "Hello, what can you do?"
```

## Running Tests

```bash
pytest
```

## Production Deployment

To connect real model providers, edit `agent.yaml` to declare your provider with an `env://` secret reference:

```yaml
providers:
  openai:
    type: openai
    api_key: env://OPENAI_API_KEY
    default_model: gpt-4o-mini
```
"""
    return {
        "agent.yaml": agent_yaml,
        "app.py": app_py,
        "test_agent.py": test_py,
        "README.md": readme_md,
        ".gitignore": _gitignore_content(),
        "traccia.toml.example": _traccia_example_content(),
    }


def _approval_template(slug: str, ident: str) -> dict[str, str]:
    workflow_name = f"{slug}-workflow"
    agent_yaml = f"""providers:
  mock:
    type: mock
    default_model: deterministic

agents:
  - name: {slug}-proposer
    version: 1.0.0
    description: Generates bounded proposals for human review
    system_instructions: Return only structured proposals.
    default_model:
      name: default
      provider: mock
      model: deterministic
    planning_strategy: direct
    max_steps: 3

workflows:
  {workflow_name}:
    name: {workflow_name}
    version: 1.0.0
    description: Proposal, human approval checkpoint, and idempotent apply
    hook_provider: hooks:create_hooks
    nodes:
      - id: propose
        kind: agent
        agent: {slug}-proposer
        input_builder: proposal.builder
        output_schema_hook: proposal.schema
        output_key: proposal
      - id: approve
        kind: approval
        depends_on: [propose]
        output_key: approval
        approval:
          prompt: Review this change before it is applied.
          review_from: [proposal.change]
          parameters_from: proposal.parameters
          parameters_schema:
            type: object
            required: [change]
            properties:
              change: {{type: string, minLength: 1}}
            additionalProperties: false
          allow_modification: true
          rejection_policy: skip_dependents
          expires_seconds: 1800
      - id: apply
        kind: handler
        depends_on: [approve]
        handler: proposal.apply
        output_key: result
"""

    hooks_py = """from __future__ import annotations

from typing import Any
from algen_agent_runtime.workflows import WorkflowHookRegistry

PROPOSAL_SCHEMA = {
    "type": "object",
    "required": ["change", "parameters"],
    "properties": {
        "change": {"type": "string"},
        "parameters": {
            "type": "object",
            "required": ["change"],
            "properties": {"change": {"type": "string"}},
        },
    },
}


def create_hooks(**_: Any) -> WorkflowHookRegistry:
    hooks = WorkflowHookRegistry()
    hooks.register_schema("proposal.schema", PROPOSAL_SCHEMA)

    def propose(context: Any) -> dict[str, Any]:
        change = str(context.state.values.get("question", "Default action"))
        return {"change": change, "parameters": {"change": change}}

    def apply(context: Any) -> dict[str, Any]:
        approval = context.state.values["approval"]
        return {
            "status": "applied",
            "parameters": approval.get("parameters"),
            "idempotency_key": f"approval:{context.state.id}",
        }

    hooks.register_builder("proposal.builder", propose)
    hooks.register_handler("proposal.apply", apply)
    return hooks
"""

    app_py = f'''from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path
from typing import Any

from algen_agent_runtime.config.settings import load_settings
from algen_agent_runtime.orchestration.container import build_container
from algen_agent_runtime.runtime.client import AlgenAgentRuntimeClient
from algen_agent_runtime.workflows import (
    MultiAgentWorkflowExecutor,
    WorkflowRegistry,
    WorkflowStatus,
)
from hooks import create_hooks


async def run(question: str, decision: str = "approved") -> dict[str, Any]:
    """Execute the {workflow_name} workflow with the given approval decision."""
    config_path = Path(__file__).with_name("agent.yaml")
    settings = load_settings((config_path,))
    manifest = settings.workflows["{workflow_name}"]
    container = build_container(settings)
    try:
        registry = WorkflowRegistry()
        hooks = create_hooks()
        registry.register(manifest, hooks)

        executor = MultiAgentWorkflowExecutor(
            AlgenAgentRuntimeClient(container.runtime),
            hooks,
            store=container.workflow_checkpoints,
            workflow_registry=registry,
        )
        state = await executor.run(
            manifest,
            {{"question": question, "input": question}},
            tenant_id="default-tenant",
            user_id="default-user",
        )
        while state.status in {{
            WorkflowStatus.AWAITING_INPUT,
            WorkflowStatus.AWAITING_APPROVAL,
        }}:
            if state.status is WorkflowStatus.AWAITING_APPROVAL:
                state = await executor.decide_approval(
                    manifest,
                    state.id,
                    tenant_id="default-tenant",
                    user_id="default-user",
                    decision=decision,
                )
            else:
                break
        return state.values
    finally:
        container.close()


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Run {workflow_name}")
    parser.add_argument("change", nargs="?", default="Apply synthetic modification")
    parser.add_argument(
        "--decision",
        choices=["approved", "rejected"],
        default="approved",
        help="Approval decision (default: approved)",
    )
    args = parser.parse_args(argv)

    values = asyncio.run(run(args.change, decision=args.decision))
    print(json.dumps(values, indent=2, default=str))


if __name__ == "__main__":
    main()
'''

    test_py = """from __future__ import annotations

import pytest
from app import run


@pytest.mark.asyncio
async def test_approval_workflow_approve() -> None:
    values = await run("Test change", decision="approved")
    assert values["approval"]["decision"] == "approved"
    assert values["result"]["status"] == "applied"


@pytest.mark.asyncio
async def test_approval_workflow_reject() -> None:
    values = await run("Test change", decision="rejected")
    assert values["approval"]["decision"] == "rejected"
    assert "result" not in values
"""

    readme_md = f"""# {slug} (Approval Workflow)

A human-gated workflow built with [Algen Agent Runtime](https://github.com/AlgenAI/algen-agent-runtime).

## Running Interactively / Headless

```bash
# Run with approval (default)
python app.py "Apply synthetic modification"

# Run with rejection
python app.py "Apply synthetic modification" --decision rejected
```

## Running Tests

```bash
pytest
```
"""
    return {
        "agent.yaml": agent_yaml,
        "hooks.py": hooks_py,
        "app.py": app_py,
        "test_agent.py": test_py,
        "README.md": readme_md,
        ".gitignore": _gitignore_content(),
        "traccia.toml.example": _traccia_example_content(),
    }


def _workflow_template(slug: str, ident: str) -> dict[str, str]:
    workflow_name = f"{slug}-dag"
    agent_yaml = f"""providers:
  mock:
    type: mock
    default_model: deterministic

agents:
  - name: {slug}-worker
    version: 1.0.0
    description: Worker agent that analyzes tasks
    system_instructions: Analyze the task and return concise findings.
    default_model:
      name: default
      provider: mock
      model: deterministic
    planning_strategy: direct
    max_steps: 3

workflows:
  {workflow_name}:
    name: {workflow_name}
    version: 1.0.0
    description: Deterministic multi-stage DAG workflow
    hook_provider: hooks:create_hooks
    nodes:
      - id: step-one
        kind: handler
        handler: workflow.step_one
        output_key: step_one_data
      - id: step-two
        kind: agent
        depends_on: [step-one]
        agent: {slug}-worker
        input_template: "{{{{step_one_data.input}}}}"
        output_key: worker_analysis
      - id: step-three
        kind: handler
        depends_on: [step-two]
        handler: workflow.step_three
        output_key: final_summary
"""

    hooks_py = """from __future__ import annotations

from typing import Any
from algen_agent_runtime.workflows import WorkflowHookRegistry


def create_hooks(**_: Any) -> WorkflowHookRegistry:
    hooks = WorkflowHookRegistry()

    def step_one(context: Any) -> dict[str, Any]:
        return {"prepared": True, "input": context.state.values.get("question", "")}

    def step_three(context: Any) -> dict[str, Any]:
        return {
            "status": "completed",
            "summary": "Workflow completed successfully",
            "analysis": context.state.values.get("worker_analysis", {}),
        }

    hooks.register_handler("workflow.step_one", step_one)
    hooks.register_handler("workflow.step_three", step_three)
    return hooks
"""

    app_py = f'''from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path
from typing import Any

from algen_agent_runtime.config.settings import load_settings
from algen_agent_runtime.orchestration.container import build_container
from algen_agent_runtime.runtime.client import AlgenAgentRuntimeClient
from algen_agent_runtime.workflows import (
    MultiAgentWorkflowExecutor,
    WorkflowRegistry,
)
from hooks import create_hooks


async def run(question: str) -> dict[str, Any]:
    """Execute the {workflow_name} workflow."""
    config_path = Path(__file__).with_name("agent.yaml")
    settings = load_settings((config_path,))
    manifest = settings.workflows["{workflow_name}"]
    container = build_container(settings)
    try:
        registry = WorkflowRegistry()
        hooks = create_hooks()
        registry.register(manifest, hooks)

        executor = MultiAgentWorkflowExecutor(
            AlgenAgentRuntimeClient(container.runtime),
            hooks,
            store=container.workflow_checkpoints,
            workflow_registry=registry,
        )
        state = await executor.run(
            manifest,
            {{"question": question, "input": question}},
            tenant_id="default-tenant",
            user_id="default-user",
        )
        return state.values
    finally:
        container.close()


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Run {workflow_name}")
    parser.add_argument("question", nargs="?", default="Analyze quarterly trends")
    args = parser.parse_args(argv)

    values = asyncio.run(run(args.question))
    print(json.dumps(values, indent=2, default=str))


if __name__ == "__main__":
    main()
'''

    test_py = """from __future__ import annotations

import pytest
from app import run


@pytest.mark.asyncio
async def test_workflow_runs_end_to_end() -> None:
    values = await run("Test question")
    assert values["final_summary"]["status"] == "completed"
"""

    readme_md = f"""# {slug} (DAG Workflow)

A multi-stage DAG workflow built with [Algen Agent Runtime](https://github.com/AlgenAI/algen-agent-runtime).

## Running the Workflow

```bash
python app.py "Analyze quarterly trends"
```

## Running Tests

```bash
pytest
```
"""
    return {
        "agent.yaml": agent_yaml,
        "hooks.py": hooks_py,
        "app.py": app_py,
        "test_agent.py": test_py,
        "README.md": readme_md,
        ".gitignore": _gitignore_content(),
        "traccia.toml.example": _traccia_example_content(),
    }


def scaffold_project(
    name: str,
    target_dir: str | Path,
    template: TemplateName = "agent",
    *,
    force: bool = False,
) -> Path:
    """Scaffold a new Algen Agent Runtime project deterministically."""
    if template not in AVAILABLE_TEMPLATES:
        raise ValueError(
            f"Unknown template {template!r}; available templates: {', '.join(AVAILABLE_TEMPLATES)}"
        )

    slug, ident = _sanitize_name(name)
    dest = Path(target_dir).resolve()

    if dest.exists() and any(dest.iterdir()) and not force:
        raise FileExistsError(
            f"Target directory {dest} already exists and is not empty. Use --force to overwrite."
        )

    dest.mkdir(parents=True, exist_ok=True)

    if template == "agent":
        files = _agent_template(slug, ident)
    elif template == "approval":
        files = _approval_template(slug, ident)
    elif template == "workflow":
        files = _workflow_template(slug, ident)
    else:
        raise ValueError(f"Unsupported template {template}")

    for filename, content in files.items():
        file_path = dest / filename
        file_path.write_text(content, encoding="utf-8")

    return dest
